# Number of days of inactivity before an Issue or Pull Request becomes stale.
daysUntilStale: 90

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 30

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable.
exemptLabels: ["stale/exempt", "pinned"]

# Label to use when marking as stale.
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable.
issues:
  markComment: >
    Thank you for taking the time to raise this issue. However, it has
    not had any activity on it in the past 90 days and will be closed in
    30 days if no updates occur.

    Please check if the master branch has already resolved the issue
    since it was raised. If you believe the issue is still valid and you
    would like input from the maintainers then please comment to ask for
    it to be reviewed.

pulls:
  markComment: >
    Thank you for your contribution! However, this pull request has not
    had any activity in the past 90 days and will be closed in 30 days if
    no updates occur.

    If you believe the changes are still valid then please verify your
    branch has no conflicts with master and rebase if needed. If you
    are awaiting a (re-)review then please let us know.
