FROM maven:3-jdk-8-slim

RUN apt-get update && apt-get install -y git && \
cd /opt &&  \
git clone https://github.com/FrancoisPoinsot/simplest-uncommitted-msg &&  \
cd ./simplest-uncommitted-msg &&  \
mvn clean install

  # There is still thing downloaded on `mvn exec`. I guess it download the `exec plugin`
  # This still work, but it force the download at each run instead of using local docker cache of images layer
  # TODO: add necessary config in pom.xml so that `mvn install` will install the `exec` plugin
CMD  cd /opt/simplest-uncommitted-msg && mvn exec:java -Dexec.mainClass="CustomProducer.Main" && \
echo ----------- && \
echo ready to run && \
echo -----------