name: Fuzzing
on:
  merge_group:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches:
    - "**"
    paths-ignore:
    - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read  # for actions/checkout to fetch code

env:
  # Use the Go toolchain installed by setup-go
  GOTOOLCHAIN: local

jobs:
  test:
    name: Fuzz (${{ matrix.fuzz }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fuzz:
        - FuzzVersionedDecodeRequest
        - FuzzVersionedDecodeResponse
    env:
      GOFLAGS: -trimpath
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: stable
    - name: Run fuzz target
      run: go test -v -run=^${{ matrix.fuzz }}$ -fuzz=^${{ matrix.fuzz }}$ -fuzztime=5m
    - name: Upload crasher corpus on failure
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: fuzz-crashers-${{ matrix.fuzz }}
        path: testdata/fuzz/${{ matrix.fuzz }}/
        if-no-files-found: ignore
        retention-days: 14
