name: FVT (PR)
on:
  pull_request:
    branches:
    - "**"
    paths-ignore:
    - '**/*.md'

permissions:
  contents: read  # for actions/checkout to fetch code

env:
  # Use the Go toolchain installed by setup-go
  GOTOOLCHAIN: local

jobs:
  fvt:
    name: Test with Kafka ${{ matrix.kafka-version }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [stable]
        kafka-version: [1.0.2, 2.6.3, 3.6.2, 3.9.1, 4.1.0]
        include:
        - kafka-version: 1.0.2
          scala-version: 2.11
        - kafka-version: 2.6.3
          scala-version: 2.12
        - kafka-version: 3.6.2
          scala-version: 2.13
        - kafka-version: 3.9.1
          scala-version: 2.13
        - kafka-version: 4.0.0
          scala-version: 2.13
    uses: ./.github/workflows/fvt.yml
    with:
      go-version: ${{ matrix.go-version }}
      kafka-version: ${{ matrix.kafka-version }}
      scala-version: ${{ matrix.scala-version }}
