name: renovate-config-validator

on:
  pull_request:
    paths:
      - '.github/renovate.json5'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: |
            .github/renovate.json5
          sparse-checkout-cone-mode: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      - run: npx --package=renovate@latest -- renovate-config-validator
